### ISSUE TITLE
Add stats section

### ISSUE THREAD

**Issue by fliptrail** [anweshaiitp/anwesha-web-2020#2]
Add stats section like footfall etc.
Take idea from: https://moodi.org/

**Comment by fliptrail** [comment]
160+
COLLEGES

70+
EVENTS

10+
CITIES COVERAGE

70000+
SOCIAL OUTREACH

15000+
FOOTFALL

10
EDITIONS

**Comment by Ankit7Das** [comment]
I'm interested and I wish to work for it

**Comment by fliptrail** [comment]
Ok, go forward.
