### ISSUE TITLE
The contact us backgroung image (anwesha19 group photo) slides down when mouse is moved over it.

### ISSUE THREAD

**Issue by ashwaniYDV** [anweshaiitp/anwesha-web-2020#26]
![anwwww](https://user-images.githubusercontent.com/43786728/71602571-0d2b3d80-2b7f-11ea-8758-f04653067a82.gif)

**Comment by Darshilp326** [comment]
i would like to work on this issue.

**Comment by ashwaniYDV** [comment]
@Darshilp326 Go ahead :+1:
