### ISSUE TITLE
Revamp the UI of book accomodation (Select tag, buttons etc)

### ISSUE THREAD

**Issue by ashwaniYDV** [anweshaiitp/anwesha-web-2020#29]
![ssss](https://user-images.githubusercontent.com/43786728/71726647-c6c72e80-2e5d-11ea-88c8-f2c921073cb1.png)

**Comment by ashwaniYDV** [comment]
@Darshilp326 @Ankit7Das Anyone of you take up this issue. Please beautify it.
Everything aligned centre-vertically should look great I guess.

**Comment by Ankit7Das** [comment]
I'll work on it right away
