### ISSUE TITLE
Adding links to the footer ,change the title bar and remove search button

### ISSUE THREAD

**Issue by Subhang23** [anweshaiitp/anwesha-web-2020#48]
1.All the footers have links with no destination. Link them to their respective pages.
2. There still exists a search icon in the navbar which should be removed.
3. Change the title tag to make it the same as the one in index.html

**Comment by Subhang23** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/43785080/71902410-0c4e6900-3188-11ea-847a-b9d2bc787b2d.png)
Do it also for the contact us button also

**Comment by CITIZENDOT** [comment]
I will try this.

**Comment by sk044** [comment]
I can work on this issue..
