### ISSUE TITLE
Create a FAQ section

### ISSUE THREAD

**Issue by fliptrail** [anweshaiitp/anwesha-web-2020#7]
Inspiration from: https://moodi.org/faqs/reach%20us

**Comment by Ankit7Das** [comment]
i want to work on it

**Comment by shreyaswikriti** [comment]
I would like to work on this

**Comment by fliptrail** [comment]
Okay, Go Forward.

**Comment by shreyaswikriti** [comment]
![faq](https://user-images.githubusercontent.com/57635473/71324134-428db680-2501-11ea-978e-1a3d47442539.png)

**Comment by shreyaswikriti** [comment]
background is animate .
view of faq page
